# Generated by Django 4.2 on 2023-06-07 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facebook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_account', models.CharField(choices=[('facebook', 'Facebook')], max_length=50)),
            ],
        ),
    ]
