# Generated by Django 4.2 on 2023-06-07 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Google', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='google',
            name='social_account',
            field=models.CharField(choices=[('google', 'Google')], max_length=50),
        ),
    ]
